#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""动植物图鉴 - 升级版（动物+植物）"""
import os, io, json, hashlib
from flask import Flask, request, jsonify, render_template_string, redirect, url_for, session, send_from_directory
import pymysql
from PIL import Image
from datetime import datetime as dt

app = Flask(__name__)
app.secret_key = 'bio_guide_secret_2026'
UPLOAD_FOLDER = '/root/.openclaw/workspace/bio_photos'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

DB_CONFIG = dict(host='localhost', user='root', password='OpenClaw@2026',
                 database='openclaw_db', charset='utf8mb4',
                 cursorclass=pymysql.cursors.DictCursor)

def get_db():
    return pymysql.connect(**DB_CONFIG)

def hash_password(pwd):
    return hashlib.sha256(pwd.encode()).hexdigest()

def allowed_file(fn):
    return '.' in fn and fn.rsplit('.', 1)[1].lower() in {'png', 'jpg', 'jpeg', 'gif', 'webp'}

def compress_image(stream, max_size=(1200, 1200), quality=78):
    img = Image.open(stream)
    if img.mode in ('RGBA', 'P', 'LA'):
        bg = Image.new('RGB', img.size, (255, 255, 255))
        bg.paste(img, mask=img.split()[-1] if img.mode == 'RGBA' else None)
        img = bg
    elif img.mode != 'RGB':
        img = img.convert('RGB')
    img.thumbnail(max_size, Image.LANCZOS)
    out = io.BytesIO()
    img.save(out, format='JPEG', quality=quality, optimize=True)
    out.seek(0)
    return out

PLANTS = [
    {"name_cn": "苏铁", "name_en": "Sago Palm", "scientific_name": "Cycas revoluta",
     "kingdom": "植物界", "phylum": "苏铁门", "class": "苏铁纲", "order_name": "苏铁目",
     "family": "苏铁科", "genus": "苏铁属", "species": "苏铁", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木，羽状复叶，雌雄异株，种子红色",
     "is_endangered": 0, "region": "中国南方各省区", "description": "古老的活化石植物，树形美观，生长缓慢。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "种子", "habitat": "山坡、林地"},
    {"name_cn": "银杏", "name_en": "Ginkgo", "scientific_name": "Ginkgo biloba",
     "kingdom": "植物界", "phylum": "银杏门", "class": "银杏纲", "order_name": "银杏目",
     "family": "银杏科", "genus": "银杏属", "species": "银杏", "subspecies": "",
     "category": "裸子植物", "feature": "落叶乔木，叶扇形，秋叶金黄，雌雄异株",
     "is_endangered": 0, "region": "中国各地栽培", "description": "著名活化石，寿命可达千年以上，秋色极为壮观。",
     "flower_color": "", "leaf_type": "落叶", "fruit_type": "种子", "habitat": "寺庙、园林"},
    {"name_cn": "油松", "name_en": "Chinese Pine", "scientific_name": "Pinus tabuliformis",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "松科", "genus": "松属", "species": "油松", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木，树皮龟裂，红褐色，针叶2-3枚一束",
     "is_endangered": 0, "region": "中国华北、西北", "description": "北方荒山造林先锋树种，适应性极强。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "球果", "habitat": "山坡、岩石地"},
    {"name_cn": "马尾松", "name_en": "Masson Pine", "scientific_name": "Pinus massoniana",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "松科", "genus": "松属", "species": "马尾松", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木，树皮红褐色，针叶细长2枚一束",
     "is_endangered": 0, "region": "中国秦岭-淮河以南", "description": "南方重要用材和采脂树种，松脂产量高。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "球果", "habitat": "山地、丘陵"},
    {"name_cn": "水杉", "name_en": "Dawn Redwood", "scientific_name": "Metasequoia glyptostroboides",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "杉科", "genus": "水杉属", "species": "水杉", "subspecies": "",
     "category": "裸子植物", "feature": "落叶乔木，树干笔直，落叶前叶变红褐色",
     "is_endangered": 1, "region": "中国中部（湖北、重庆）", "description": "活化石，1940年代被发现，现各地均有栽培。",
     "flower_color": "", "leaf_type": "落叶", "fruit_type": "球果", "habitat": "山谷、水边"},
    {"name_cn": "侧柏", "name_en": "Chinese Arborvitae", "scientific_name": "Platycladus orientalis",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "柏科", "genus": "侧柏属", "species": "侧柏", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木，鳞叶交互对生，球果成熟开裂",
     "is_endangered": 0, "region": "中国各地", "description": "寺庙古树常见，寿命极长，材用及观赏兼备。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "球果", "habitat": "山坡、寺庙"},
    {"name_cn": "圆柏", "name_en": "Chinese Juniper", "scientific_name": "Juniperus chinensis",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "柏科", "genus": "刺柏属", "species": "圆柏", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木或灌木，幼枝刺形叶，老枝鳞形叶",
     "is_endangered": 0, "region": "中国华北、西北", "description": "适应性强，寿命长，常见于寺庙和园林。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "球果", "habitat": "山坡、石灰岩"},
    {"name_cn": "雪松", "name_en": "Deodar Cedar", "scientific_name": "Cedrus deodara",
     "kingdom": "植物界", "phylum": "松柏门", "class": "松柏纲", "order_name": "松目",
     "family": "松科", "genus": "雪松属", "species": "雪松", "subspecies": "",
     "category": "裸子植物", "feature": "常绿乔木，塔形树冠，蓝绿色针叶下垂",
     "is_endangered": 0, "region": "中国西部高原", "description": "世界著名观赏树，树干笔直，材用价值高。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "球果", "habitat": "高海拔山地"},
    {"name_cn": "梧桐", "name_en": "Chinese Parasol Tree", "scientific_name": "Firmiana simplex",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "锦葵目",
     "family": "梧桐科", "genus": "梧桐属", "species": "梧桐", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，叶掌状裂，花黄绿色，树皮青绿色",
     "is_endangered": 0, "region": "中国黄河以南", "description": "古代被视为祥瑞之树，速生，木材轻软。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "蓇葖果", "habitat": "村边、山谷"},
    {"name_cn": "垂柳", "name_en": "Weeping Willow", "scientific_name": "Salix babylonica",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "杨柳目",
     "family": "杨柳科", "genus": "柳属", "species": "垂柳", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，枝条细长下垂，叶狭长披针形",
     "is_endangered": 0, "region": "中国各地", "description": "著名观赏树，宜植于水边，枝条婆娑。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "水边、河岸"},
    {"name_cn": "毛白杨", "name_en": "Chinese White Poplar", "scientific_name": "Populus tomentosa",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "杨柳目",
     "family": "杨柳科", "genus": "杨属", "species": "毛白杨", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，树干高大通直，叶三角状卵形，背面密被绒毛",
     "is_endangered": 0, "region": "中国华北、西北", "description": "北方重要行道树，生长快，材质好。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "平原、山地"},
    {"name_cn": "榆树", "name_en": "Siberian Elm", "scientific_name": "Ulmus pumila",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "荨麻目",
     "family": "榆科", "genus": "榆属", "species": "榆树", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，叶椭圆形，边缘重锯齿，翅果",
     "is_endangered": 0, "region": "中国各地", "description": "耐寒耐旱，寿命长，榆钱可食，木材坚硬。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "翅果", "habitat": "平原、山地"},
    {"name_cn": "槐树", "name_en": "Japanese Pagoda Tree", "scientific_name": "Sophora japonica",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "豆目",
     "family": "豆科", "genus": "槐属", "species": "槐", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，奇数羽状复叶，圆锥花序白色",
     "is_endangered": 0, "region": "中国各地", "description": "著名庭荫树和蜜源树，花可入药，木材耐腐。",
     "flower_color": "白色", "leaf_type": "落叶", "fruit_type": "荚果", "habitat": "村边、路边"},
    {"name_cn": "樟树", "name_en": "Camphor Tree", "scientific_name": "Cinnamomum camphora",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "樟目",
     "family": "樟科", "genus": "樟属", "species": "樟树", "subspecies": "",
     "category": "被子植物·乔木", "feature": "常绿乔木，叶互生有樟脑气味，圆锥花序",
     "is_endangered": 0, "region": "中国长江以南", "description": "著名用材树，全株含樟脑，气味芬芳。",
     "flower_color": "黄白色", "leaf_type": "常绿", "fruit_type": "核果", "habitat": "山坡、谷地"},
    {"name_cn": "楠木", "name_en": "Zhennan", "scientific_name": "Phoebe zhennan",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "樟目",
     "family": "樟科", "genus": "楠属", "species": "楠木", "subspecies": "",
     "category": "被子植物·乔木", "feature": "常绿乔木，叶长椭圆形，花小，圆锥花序",
     "is_endangered": 1, "region": "中国贵州、四川、云南", "description": "珍贵用材，有木中之金之称，生长缓慢。",
     "flower_color": "黄绿色", "leaf_type": "常绿", "fruit_type": "核果", "habitat": "山谷、溪边"},
    {"name_cn": "桂花", "name_en": "Sweet Olive", "scientific_name": "Osmanthus fragrans",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "唇形目",
     "family": "木犀科", "genus": "木犀属", "species": "桂花", "subspecies": "",
     "category": "被子植物·乔木", "feature": "常绿乔木或灌木，叶对生，花小而香，有金桂银桂丹桂等",
     "is_endangered": 0, "region": "中国秦岭以南", "description": "著名芳香植物，花可制糕点、酿酒，香气馥郁。",
     "flower_color": "金黄色/白色", "leaf_type": "常绿", "fruit_type": "核果", "habitat": "园林、庭院"},
    {"name_cn": "白玉兰", "name_en": "Yulan Magnolia", "scientific_name": "Magnolia denudata",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "木兰目",
     "family": "木兰科", "genus": "木兰属", "species": "白玉兰", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，花大白色先叶开放，芳香，花被片9枚",
     "is_endangered": 0, "region": "中国中部、东部", "description": "著名观赏花木，早春开花如雪，香气袭人。",
     "flower_color": "白色", "leaf_type": "落叶", "fruit_type": "聚合蓇葖果", "habitat": "园林、寺庙"},
    {"name_cn": "枫杨", "name_en": "Chinese Wingnut", "scientific_name": "Pterocarya stenoptera",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "胡桃目",
     "family": "胡桃科", "genus": "枫杨属", "species": "枫杨", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，羽状复叶，小叶长椭圆形，翅果成串",
     "is_endangered": 0, "region": "中国华北以南", "description": "常见行道树和护堤树种，寿命长。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "翅果", "habitat": "水边、平原"},
    {"name_cn": "朴树", "name_en": "Chinese Hackberry", "scientific_name": "Celtis sinensis",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "蔷薇目",
     "family": "大麻科", "genus": "朴属", "species": "朴树", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，叶卵形，基部偏斜，核果橙红色",
     "is_endangered": 0, "region": "中国中部、南方", "description": "优良庭荫树，树形优美，寿命长。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "核果", "habitat": "村边、山坡"},
    {"name_cn": "杜仲", "name_en": "Hard Rubber Tree", "scientific_name": "Eucommia ulmoides",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "榆目",
     "family": "杜仲科", "genus": "杜仲属", "species": "杜仲", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，叶椭圆形，折断有银白色胶丝",
     "is_endangered": 1, "region": "中国中部（湖南、湖北、四川）", "description": "中国特有经济树种，树皮入药，胶丝工业用途广。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "翅果", "habitat": "山谷、山坡"},
    {"name_cn": "鹅掌楸", "name_en": "Chinese Tulip Tree", "scientific_name": "Liriodendron chinense",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "木兰目",
     "family": "木兰科", "genus": "鹅掌楸属", "species": "鹅掌楸", "subspecies": "",
     "category": "被子植物·乔木", "feature": "落叶乔木，叶马褂形（两侧各1裂），花黄绿色杯状",
     "is_endangered": 1, "region": "中国长江以南", "description": "活化石孑遗植物，叶形奇特如清代马褂。",
     "flower_color": "黄绿色", "leaf_type": "落叶", "fruit_type": "聚合果", "habitat": "山地、沟谷"},
    {"name_cn": "杜鹃", "name_en": "Azalea", "scientific_name": "Rhododendron simsii",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "杜鹃花目",
     "family": "杜鹃花科", "genus": "杜鹃花属", "species": "杜鹃", "subspecies": "",
     "category": "被子植物·灌木", "feature": "常绿或落叶灌木，花漏斗形，2-6朵簇生，红紫色为主",
     "is_endangered": 0, "region": "中国长江以南", "description": "著名观赏花卉，春夏之交漫山红艳，品种繁多。",
     "flower_color": "红色/紫色/白色", "leaf_type": "常绿/落叶", "fruit_type": "蒴果", "habitat": "山地、林缘"},
    {"name_cn": "山茶", "name_en": "Camellia", "scientific_name": "Camellia japonica",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "侧膜胎座目",
     "family": "山茶科", "genus": "山茶属", "species": "山茶", "subspecies": "",
     "category": "被子植物·灌木", "feature": "常绿灌木或小乔木，叶深绿色有光泽，花大红色",
     "is_endangered": 0, "region": "中国东部、南部", "description": "著名观赏花卉，与梅花、水仙并称雪中四友。",
     "flower_color": "红色/白色/粉色", "leaf_type": "常绿", "fruit_type": "蒴果", "habitat": "山地、园林"},
    {"name_cn": "茉莉", "name_en": "Arabian Jasmine", "scientific_name": "Jasminum sambac",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "唇形目",
     "family": "木犀科", "genus": "素馨属", "species": "茉莉", "subspecies": "",
     "category": "被子植物·灌木", "feature": "常绿缠绕灌木，叶对生，花白色芳香，单瓣或重瓣",
     "is_endangered": 0, "region": "中国南方各省", "description": "著名芳香植物，花可窨茶，香气世界著名。",
     "flower_color": "白色", "leaf_type": "常绿", "fruit_type": "浆果", "habitat": "园林、庭院"},
    {"name_cn": "紫薇", "name_en": "Crape Myrtle", "scientific_name": "Lagerstroemia indica",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "桃金娘目",
     "family": "千屈菜科", "genus": "紫薇属", "species": "紫薇", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木或小乔木，树皮光滑，花序顶生，有柄",
     "is_endangered": 0, "region": "中国华东、华中", "description": "著名观赏树，树龄长，有痒痒树之称。",
     "flower_color": "紫色/粉色/白色", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "园林、路边"},
    {"name_cn": "绣球", "name_en": "Bigleaf Hydrangea", "scientific_name": "Hydrangea macrophylla",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "山茱萸目",
     "family": "绣球科", "genus": "绣球属", "species": "绣球", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木，叶对生，花序球形不育花组成，蓝紫粉白",
     "is_endangered": 0, "region": "中国华东", "description": "著名观赏花卉，花序大而艳，雨天更蓝。",
     "flower_color": "蓝色/紫色/粉色/白色", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "林下、园林"},
    {"name_cn": "枸杞", "name_en": "Wolfberry", "scientific_name": "Lycium barbarum",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "茄目",
     "family": "茄科", "genus": "枸杞属", "species": "枸杞", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶多分枝灌木，枝条常俯垂，有刺，叶披针形",
     "is_endangered": 0, "region": "中国西北、华北", "description": "著名药用植物，果实枸杞子滋补肝肾。",
     "flower_color": "紫色", "leaf_type": "落叶", "fruit_type": "浆果", "habitat": "干旱山坡、盐碱地"},
    {"name_cn": "木槿", "name_en": "Rose of Sharon", "scientific_name": "Hibiscus syriacus",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "锦葵目",
     "family": "锦葵科", "genus": "木槿属", "species": "木槿", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木，叶菱形，花大单生，有单瓣重瓣，花期长",
     "is_endangered": 0, "region": "中国各地", "description": "著名观赏花卉，朝开幕落，花期整个夏季。",
     "flower_color": "紫红/粉/白", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "园林、路边"},
    {"name_cn": "连翘", "name_en": "Golden Bell", "scientific_name": "Forsythia suspensa",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "唇形目",
     "family": "木犀科", "genus": "连翘属", "species": "连翘", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木，枝条中空或片状髓，花金黄色先叶开放",
     "is_endangered": 0, "region": "中国中部、北方", "description": "早春开花植物，花金黄灿烂，迎春而生。",
     "flower_color": "金黄色", "leaf_type": "落叶", "fruit_type": "蒴果", "habitat": "山坡、林缘"},
    {"name_cn": "迎春", "name_en": "Winter Jasmine", "scientific_name": "Jasminum nudiflorum",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "唇形目",
     "family": "木犀科", "genus": "素馨属", "species": "迎春", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木，枝条绿色四棱，花小黄色先叶开放",
     "is_endangered": 0, "region": "中国中部、西北", "description": "著名早春花卉，与梅花、水仙并称雪中三友。",
     "flower_color": "黄色", "leaf_type": "落叶", "fruit_type": "浆果", "habitat": "山坡、墙垣"},
    {"name_cn": "红继木", "name_en": "Hongka Muhly", "scientific_name": "Loropetalum chinense",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "山茱萸目",
     "family": "金缕梅科", "genus": "继木属", "species": "红继木", "subspecies": "",
     "category": "被子植物·灌木", "feature": "常绿灌木，叶紫红色，花丝状红色",
     "is_endangered": 0, "region": "中国南方", "description": "著名彩叶植物，红叶紫花，园林中广泛应用。",
     "flower_color": "红色/白色", "leaf_type": "常绿", "fruit_type": "蒴果", "habitat": "山地、林缘"},
    {"name_cn": "紫玉兰", "name_en": "Lily Magnolia", "scientific_name": "Magnolia liliiflora",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "木兰目",
     "family": "木兰科", "genus": "木兰属", "species": "紫玉兰", "subspecies": "",
     "category": "被子植物·灌木", "feature": "落叶灌木，花紫色先叶开放，花被片9枚，外层较小",
     "is_endangered": 0, "region": "中国中部", "description": "观赏花卉，花大色艳，与白玉兰齐名。",
     "flower_color": "紫色", "leaf_type": "落叶", "fruit_type": "聚合蓇葖果", "habitat": "园林"},
    {"name_cn": "兰草", "name_en": "Chinese Orchid", "scientific_name": "Cymbidium goeringii",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "单子叶纲", "order_name": "兰目",
     "family": "兰科", "genus": "兰属", "species": "春兰", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生草本，叶线形基生，花清香，通常一茎一花",
     "is_endangered": 1, "region": "中国中部、西南", "description": "中国十大名花之首，有王者之香美誉，文化底蕴深厚。",
     "flower_color": "绿色/黄绿色", "leaf_type": "常绿", "fruit_type": "蒴果", "habitat": "林下、石壁"},
    {"name_cn": "菊花", "name_en": "Chrysanthemum", "scientific_name": "Chrysanthemum morifolium",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "菊目",
     "family": "菊科", "genus": "菊属", "species": "菊花", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生草本，叶互生有锯齿，头状花序，品种极多",
     "is_endangered": 0, "region": "中国各地栽培", "description": "中国十大名花之一，品种逾千，秋菊傲霜。",
     "flower_color": "黄/白/红/紫", "leaf_type": "落叶", "fruit_type": "瘦果", "habitat": "园林、庭院"},
    {"name_cn": "荷花", "name_en": "Lotus", "scientific_name": "Nelumbo nucifera",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "双子叶纲", "order_name": "山龙眼目",
     "family": "莲科", "genus": "莲属", "species": "莲", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生水生草本，根茎膨大成莲藕，叶盾圆形，花大艳丽",
     "is_endangered": 0, "region": "中国各地", "description": "中国著名花卉，出淤泥而不染，根茎花叶均有用。",
     "flower_color": "粉红色/白色", "leaf_type": "常绿", "fruit_type": "坚果", "habitat": "池塘、湖泊"},
    {"name_cn": "毛竹", "name_en": "Moso Bamboo", "scientific_name": "Phyllostachys edulis",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "单子叶纲", "order_name": "禾本目",
     "family": "禾本科", "genus": "毛竹属", "species": "毛竹", "subspecies": "",
     "category": "被子植物·草本", "feature": "大型禾草，茎木质化中空有节，叶披针形，笋可食",
     "is_endangered": 0, "region": "中国长江以南", "description": "世界上最重要的经济竹种，竹材用途极广，春笋味美。",
     "flower_color": "", "leaf_type": "常绿", "fruit_type": "颖果", "habitat": "山地、丘陵"},
    {"name_cn": "鸢尾", "name_en": "Iris", "scientific_name": "Iris tectorum",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "单子叶纲", "order_name": "百合目",
     "family": "鸢尾科", "genus": "鸢尾属", "species": "鸢尾", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生草本，叶基生剑形，蓝紫色花，外轮3枚下垂",
     "is_endangered": 0, "region": "中国中部、西南", "description": "著名观赏花卉，园林中广泛应用，根茎入药。",
     "flower_color": "蓝紫色", "leaf_type": "常绿", "fruit_type": "蒴果", "habitat": "林下、水边"},
    {"name_cn": "君子兰", "name_en": "Scarlet Kaffir Lily", "scientific_name": "Clivia miniata",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "单子叶纲", "order_name": "百合目",
     "family": "石蒜科", "genus": "君子兰属", "species": "君子兰", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生草本，叶带状基生，伞形花序，橙红色花",
     "is_endangered": 0, "region": "中国各地栽培", "description": "著名温室花卉，春节前后开花，增添喜庆气氛。",
     "flower_color": "橙红色", "leaf_type": "常绿", "fruit_type": "浆果", "habitat": "室内、园林"},
    {"name_cn": "水仙", "name_en": "Narcissus", "scientific_name": "Narcissus tazetta",
     "kingdom": "植物界", "phylum": "被子植物门", "class": "单子叶纲", "order_name": "百合目",
     "family": "石蒜科", "genus": "水仙属", "species": "水仙", "subspecies": "",
     "category": "被子植物·草本", "feature": "多年生草本，鳞茎，叶带状，伞形花序，白色副花冠黄色",
     "is_endangered": 0
