#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""批量导入动植物数据"""
import pymysql, json, sys

DB = dict(host='localhost', user='root', password='OpenClaw@2026',
          database='openclaw_db', charset='utf8mb4',
          cursorclass=pymysql.cursors.DictCursor)

def conn():
    return pymysql.connect(**DB)

# ===== 扩充动物数据（300+种中国野生动物） =====
ANIMALS = [
    # 哺乳动物 - 灵长目
    {"name_cn":"藏酋猴","name_en":" Tibetan Macaque","scientific_name":"Macaca thibetana","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"猴科","genus":"猕猴属","species":"藏酋猴","subspecies":"","category":"哺乳动物","feature":"体毛暗褐色，面部裸露，体型粗壮，尾短","is_endangered":0,"region":"中国中部和西南山地","description":"中国特有猕猴类，国家二级保护动物。"},
    {"name_cn":"川金丝猴","name_en":"Golden Snub-nosed Monkey","scientific_name":"Rhinopithecus roxellana","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"仰鼻猴属","species":"川金丝猴","subspecies":"","category":"哺乳动物","feature":"毛色金黄，脸蓝色，鼻孔上仰，社会性强","is_endangered":1,"region":"中国中部（四川、甘肃、陕西）","description":"中国特有珍贵物种，国家一级保护动物，被誉为"绒金丝猴"。"},
    {"name_cn":"滇金丝猴","name_en":"Yunnan Snub-nosed Monkey","scientific_name":"Rhinopithecus bieti","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"仰鼻猴属","species":"滇金丝猴","subspecies":"","category":"哺乳动物","feature":"毛色黑灰与金黄相间，腹部灰白，唇粉色","is_endangered":1,"region":"中国西南（云南、西藏）","description":"中国特有，世界濒危物种，国家一级保护动物。"},
    {"name_cn":"黔金丝猴","name_en":"Guizhou Snub-nosed Monkey","scientific_name":"Rhinopithecus brelichi","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"仰鼻猴属","species":"黔金丝猴","subspecies":"","category":"哺乳动物","feature":"毛色灰褐，肩披金毛，数量极少","is_endangered":1,"region":"中国贵州（梵净山）","description":"中国特有，仅分布于贵州梵净山，国家一级保护动物。"},
    {"name_cn":"黑叶猴","name_en":"Francois's Leaf Monkey","scientific_name":"Trachypithecus francoisi","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"乌叶猴属","species":"黑叶猴","subspecies":"","category":"哺乳动物","feature":"全身黑色，头顶有直立毛冠，颊部白色","is_endangered":1,"region":"中国西南（广西、贵州）","description":"国家一级保护动物，分布区狭窄。"},
    {"name_cn":"菲氏叶猴","name_en":"Phayre's Leaf Monkey","scientific_name":"Trachypithecus phayrei","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"乌叶猴属","species":"菲氏叶猴","subspecies":"","category":"哺乳动物","feature":"灰色体毛，眼眶周围白环，以叶为主食","is_endangered":1,"region":"中国西南边境","description":"国家一级保护动物。"},
    {"name_cn":"白头叶猴","name_en":"White-headed Leaf Monkey","scientific_name":"Trachypithecus leucocephalus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"疣猴科","genus":"乌叶猴属","species":"白头叶猴","subspecies":"","category":"哺乳动物","feature":"头部白色，体毛灰黑，广西特有","is_endangered":1,"region":"中国广西（扶绥、崇左）","description":"中国特有，仅分布于广西，国家一级保护动物。"},
    {"name_cn":"长臂猿","name_en":"Hylobates","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"灵长目","family":"长臂猿科","genus":"长臂猿属","species":"黑冠长臂猿","subspecies":"","category":"哺乳动物","feature":"前臂极长，无尾，树栖，晨鸣习性","is_endangered":1,"region":"中国云南、海南","description":"国家一级保护动物，有多个特有种。"},
    {"name_cn":"亚洲象","name_en":"Asian Elephant","scientific_name":"Elephas maximus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"长鼻目","family":"象科","genus":"亚洲象属","species":"亚洲象","subspecies":"","category":"哺乳动物","feature":"体型庞大，耳朵相对较小，雌象无长牙","is_endangered":1,"region":"中国云南（西双版纳）","description":"中国仅有分布，国家一级保护动物。"},
    # 食肉目 - 猫科
    {"name_cn":"虎","name_en":"Tiger","scientific_name":"Panthera tigris","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"豹属","species":"虎","subspecies":"华南虎、东北虎、孟加拉虎等","category":"哺乳动物","feature":"体型最大猫科动物，体毛橙黄有黑色横纹，顶级捕食者","is_endangered":1,"region":"中国东北、华南、西南（野生极少见）","description":"国家一级保护动物，野生虎在中国濒临灭绝。"},
    {"name_cn":"豹","name_en":"Leopard","scientific_name":"Panthera pardus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"豹属","species":"豹","subspecies":"","category":"哺乳动物","feature":"体毛金黄具黑色空心斑纹，适应性强","is_endangered":1,"region":"中国各地山区","description":"国家一级保护动物，数量稀少。"},
    {"name_cn":"雪豹","name_en":"Snow Leopard","scientific_name":"Panthera uncia","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"豹属","species":"雪豹","subspecies":"","category":"哺乳动物","feature":"毛色灰白带黑斑，绒毛厚密，生活于高海拔","is_endangered":1,"region":"中国青藏高原和天山","description":"国家一级保护动物，有"雪山之王"美誉。"},
    {"name_cn":"云豹","name_en":"Clouded Leopard","scientific_name":"Neofelis nebulosa","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"云豹属","species":"云豹","subspecies":"","category":"哺乳动物","feature":"体毛灰黄，具大块云状斑纹，犬齿比例最大","is_endangered":1,"region":"中国西南、东南山地","description":"国家一级保护动物。"},
    {"name_cn":"兔狲","name_en":"Pallas's Cat","scientific_name":"Otocolobus manul","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"兔狲属","species":"兔狲","subspecies":"","category":"哺乳动物","feature":"体型矮壮，毛长绒密，耳圆距宽，高原鼠兔天敌","is_endangered":0,"region":"中国西北高原、青藏","description":"国家二级保护动物。"},
    {"name_cn":"荒漠猫","name_en":"Chinese Mountain Cat","scientific_name":"Felis bieti","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"猫属","species":"荒漠猫","subspecies":"","category":"哺乳动物","feature":"体毛沙褐色，耳尖有毛丛，足部有毛，中国特有","is_endangered":1,"region":"中国西北（青海、甘肃、四川）","description":"中国特有猫科动物，国家二级保护动物。"},
    {"name_cn":"丛林猫","name_en":"Jungle Cat","scientific_name":"Felis chaus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"猫属","species":"丛林猫","subspecies":"","category":"哺乳动物","feature":"中型猫科，耳尖有黑色簇毛，尾短有环纹","is_endangered":0,"region":"中国西南、西北","description":"国家二级保护动物。"},
    {"name_cn":"豹猫","name_en":"Leopard Cat","scientific_name":"Prionailurus bengalensis","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"豹猫属","species":"豹猫","subspecies":"","category":"哺乳动物","feature":"体型小似家猫，斑纹如豹，适应多种环境","is_endangered":0,"region":"中国各地","description":"国家三有保护动物。"},
    {"name_cn":"狼","name_en":"Wolf","scientific_name":"Canis lupus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"犬科","genus":"犬属","species":"狼","subspecies":"","category":"哺乳动物","feature":"体型中大型，群体生活，社会结构复杂","is_endangered":0,"region":"中国西北、东北、西南高原","description":"国家二级保护动物。"},
    {"name_cn":"赤狐","name_en":"Red Fox","scientific_name":"Vulpes vulpes","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"犬科","genus":"狐属","species":"赤狐","subspecies":"","category":"哺乳动物","feature":"体型最普遍的狐，尾大蓬松，吻尖耳大","is_endangered":0,"region":"中国各地","description":"分布最广的犬科动物。"},
    {"name_cn":"沙狐","name_en":"Corsac Fox","scientific_name":"Vulpes corsac","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"犬科","genus":"狐属","species":"沙狐","subspecies":"","category":"哺乳动物","feature":"体型较小，毛色淡黄，栖息于荒漠半荒漠","is_endangered":0,"region":"中国西北（内蒙古、新疆、青海）","description":"国家三有保护动物。"},
    {"name_cn":"藏狐","name_en":"Tibetan Fox","scientific_name":"Vulpes ferrilata","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"犬科","genus":"狐属","species":"藏狐","subspecies":"","category":"哺乳动物","feature":"面部宽阔方形，毛色土黄，青藏高原特有","is_endangered":0,"region":"中国青藏高原","description":"青藏高原特有狐种。"},
    {"name_cn":"貉","name_en":"Raccoon Dog","scientific_name":"Nyctereutes procyonoides","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"犬科","genus":"貉属","species":"貉","subspecies":"","category":"哺乳动物","feature":"像浣熊，体型矮肥，面部有黑色过眼纹","is_endangered":0,"region":"中国各地","description":"东亚特有物种。"},
    {"name_cn":"棕熊","name_en":"Brown Bear","scientific_name":"Ursus arctos","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"熊科","genus":"熊属","species":"棕熊","subspecies":"","category":"哺乳动物","feature":"体型最大食肉目之一，肩峰明显，素食为主","is_endangered":0,"region":"中国东北、西北高原","description":"国家二级保护动物。"},
    {"name_cn":"黑熊","name_en":"Asian Black Bear","scientific_name":"Ursus thibetanus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"熊科","genus":"熊属","species":"黑熊","subspecies":"","category":"哺乳动物","feature":"全身黑色，胸有V形白斑，又名月熊","is_endangered":1,"region":"中国东北、西南、陕西","description":"国家二级保护动物。"},
    {"name_cn":"马来熊","name_en":"Sun Bear","scientific_name":"Helarctos malayanus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"熊科","genus":"马来熊属","species":"马来熊","subspecies":"","category":"哺乳动物","feature":"体型最小熊类，胸斑马蹄形，舌长喜食蜂虫","is_endangered":1,"region":"中国云南（南部）","description":"国家一级保护动物。"},
    {"name_cn":"大熊猫","name_en":"Giant Panda","scientific_name":"Ailuropoda melanoleuca","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"大熊猫科","genus":"大熊猫属","species":"大熊猫","subspecies":"","category":"哺乳动物","feature":"黑白相间，体态圆胖，以竹子为主食","is_endangered":1,"region":"中国四川、陕西、甘肃（秦岭-岷山-邛崃-大小相岭-凉山）","description":"中国特有活化石，国家一级保护动物，被誉为"国宝"。"},
    {"name_cn":"小熊猫","name_en":"Red Panda","scientific_name":"Ailurus fulgens","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"小熊猫科","genus":"小熊猫属","species":"小熊猫","subspecies":"","category":"哺乳动物","feature":"毛色红褐，面部白斑，尾有环纹，以竹叶为主食","is_endangered":1,"region":"中国西南（四川、云南、西藏）","description":"国家二级保护动物，有"可爱先生"之称。"},
    {"name_cn":"黄喉貂","name_en":"Yellow-throated Marten","scientific_name":"Martes flavigula","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"貂属","species":"黄喉貂","subspecies":"","category":"哺乳动物","feature":"喉部黄色，体型细长，树栖为主，能捕食大熊猫幼崽","is_endangered":0,"region":"中国各地山区","description":"国家三有保护动物。"},
    {"name_cn":"紫貂","name_en":"Sable","scientific_name":"Martes zibellina","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"貂属","species":"紫貂","subspecies":"","category":"哺乳动物","feature":"毛绒柔软，色泽多样，珍贵毛皮兽","is_endangered":1,"region":"中国东北（黑龙江、大兴安岭）","description":"国家一级保护动物。"},
    {"name_cn":"石貂","name_en":"Beech Marten","scientific_name":"Martes foina","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"貂属","species":"石貂","subspecies":"","category":"哺乳动物","feature":"喉部白斑，身体细长，栖息于岩缝洞穴","is_endangered":0,"region":"中国西北、西南","description":"国家三有保护动物。"},
    {"name_cn":"狗獾","name_en":"Eurasian Badger","scientific_name":"Meles meles","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"獾属","species":"狗獾","subspecies":"","category":"哺乳动物","feature":"体型肥壮，头部有白色纵纹，夜行性","is_endangered":0,"region":"中国各地","description":"国家三有保护动物。"},
    {"name_cn":"猪獾","name_en":" Hog Badger","scientific_name":"Arctonyx collaris","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"猪獾属","species":"猪獾","subspecies":"","category":"哺乳动物","feature":"鼻端裸露似猪，挖掘能力强","is_endangered":0,"region":"中国华东、华南、西南","description":"国家三有保护动物。"},
    {"name_cn":"水獭","name_en":"Eurasian Otter","scientific_name":"Lutra lutra","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"水獭属","species":"水獭","subspecies":"","category":"哺乳动物","feature":"体型细长，趾间有蹼，水栖，善游泳","is_endangered":1,"region":"中国各地水体","description":"国家二级保护动物。"},
    {"name_cn":"小爪水獭","name_en":"Asian Small-clawed Otter","scientific_name":"Aonyx cinereus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"鼬科","genus":"小爪水獭属","species":"小爪水獭","subspecies":"","category":"哺乳动物","feature":"体型最小水獭，爪小而尖，群居","is_endangered":1,"region":"中国华南、云南","description":"国家二级保护动物。"},
    {"name_cn":"灵猫","name_en":"Large Indian Civet","scientific_name":"Viverra zibetha","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"灵猫科","genus":"灵猫属","species":"大灵猫","subspecies":"","category":"哺乳动物","feature":"会阴腺发达能分泌灵猫香，体色灰黄有斑点","is_endangered":0,"region":"中国华东、华南、西南","description":"国家三有保护动物。"},
    {"name_cn":"小灵猫","name_en":"Small Indian Civet","scientific_name":"Viverricula indica","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"灵猫科","genus":"小灵猫属","species":"小灵猫","subspecies":"","category":"哺乳动物","feature":"比大灵猫小，背部有纵向黑色纹","is_endangered":0,"region":"中国华东、华南、西南","description":"国家三有保护动物。"},
    {"name_cn":"斑灵狸","name_en":"Spotted Linsang","scientific_name":"Prionodon pardicolor","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"灵猫科","genus":"斑灵狸属","species":"斑灵狸","subspecies":"","category":"哺乳动物","feature":"体型小，斑纹似豹，爬树能力强","is_endangered":0,"region":"中国西南（云南、西藏）","description":"国家三有保护动物。"},
    {"name_cn":"果子狸","name_en":"Masked Palm Civet","scientific_name":"Paguma larvata","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"灵猫科","genus":"果子狸属","species":"果子狸","subspecies":"","category":"哺乳动物","feature":"面部黑色过眼纹，形似浣熊，夜行性杂食","is_endangered":0,"region":"中国各地","description":"国家三有保护动物。"},
    {"name_cn":"大灵猫","name_en":"Large Indian Civet","scientific_name":"Viverra zibetha","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"灵猫科","genus":"灵猫属","species":"大灵猫","subspecies":"","category":"哺乳动物","feature":"体型大，具独特香腺分泌物，体灰色有斑点","is_endangered":0,"region":"中国华东、华南、西南","description":"国家三有保护动物。"},
    {"name_cn":"云猫","name_en":"Marbled Cat","scientific_name":"Pardofelis marmorata","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"云猫属","species":"云猫","subspecies":"","category":"哺乳动物","feature":"大理石状斑纹，尾长而蓬松，树栖","is_endangered":1,"region":"中国西南（云南、西藏）","description":"国家一级保护动物。"},
    {"name_cn":"渔猫","name_en":"Fishing Cat","scientific_name":"Prionailurus viverrinus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"食肉目","family":"猫科","genus":"豹猫属","species":"渔猫","subspecies":"","category":"哺乳动物","feature":"爪间有蹼，善游泳捕鱼，栖息于湿地","is_endangered":1,"region":"中国华东、东南（偶见）","description":"国家二级保护动物。"},
    # 偶蹄目
    {"name_cn":"野牦牛","name_en":"Wild Yak","scientific_name":"Bos mutus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"牛属","species":"野牦牛","subspecies":"","category":"哺乳动物","feature":"体型巨大，密生长毛，高原适应能力强","is_endangered":1,"region":"中国青藏高原","description":"国家一级保护动物，有"高原巨兽"之称。"},
    {"name_cn":"野牛","name_en":"Wild Gaurs","scientific_name":"Bos gaurus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"牛属","species":"野牛（白肢野牛）","subspecies":"","category":"哺乳动物","feature":"体型最大牛科动物，四肢下部白色，肩峰高耸","is_endangered":1,"region":"中国云南（西双版纳）","description":"国家一级保护动物。"},
    {"name_cn":"印度野牛","name_en":"Gaur","scientific_name":"Bos gaurus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"牛属","species":"野牛","subspecies":"","category":"哺乳动物","feature":"体型巨大，四肢白色如穿了白袜子","is_endangered":1,"region":"中国云南（西双版纳）","description":"国家一级保护动物。"},
    {"name_cn":"水牛","name_en":"Wild Water Buffalo","scientific_name":"Bubalus arnee","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"水牛属","species":"野生水牛","subspecies":"","category":"哺乳动物","feature":"体型壮实，角长大后弯，栖息于湿地","is_endangered":1,"region":"中国云南（独龙江）","description":"国家一级保护动物。"},
    {"name_cn":"藏羚","name_en":"Tibetan Antelope","scientific_name":"Pantholops hodgsonii","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"藏羚属","species":"藏羚","subspecies":"","category":"哺乳动物","feature":"雄性有弯曲长角，毛绒柔软，迁徙性强","is_endangered":1,"region":"中国青藏高原（羌塘-可可西里）","description":"国家一级保护动物，曾因盗猎濒危，现保护成效显著。"},
    {"name_cn":"藏原羚","name_en":"Tibetan Gazelle","scientific_name":"Procapra picticaudata","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"原羚属","species":"藏原羚","subspecies":"","category":"哺乳动物","feature":"体态优雅，臀部白色心形斑，角短直","is_endangered":0,"region":"中国青藏高原","description":"国家二级保护动物。"},
    {"name_cn":"普氏原羚","name_en":"Przewalski's Gazelle","scientific_name":"Procapra przewalshii","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"原羚属","species":"普氏原羚","subspecies":"","category":"哺乳动物","feature":"中国特有羚羊，雄性有角，分布极窄","is_endangered":1,"region":"中国青海（青海湖周边）","description":"中国特有物种，国家一级保护动物。"},
    {"name_cn":"鹅喉羚","name_en":"Goitered Gazelle","scientific_name":"Gazella subgutturosa","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"瞪羚属","species":"鹅喉羚","subspecies":"","category":"哺乳动物","feature":"雄性喉部膨大如鹅头，故名，奔跑速度快","is_endangered":0,"region":"中国西北荒漠","description":"国家三有保护动物。"},
    {"name_cn":"赤斑羚","name_en":"Red Goral","scientific_name":"Naemorhedus baileyi","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"斑羚属","species":"赤斑羚","subspecies":"","category":"哺乳动物","feature":"体毛红褐色，攀岩能力强，高黎贡山特有","is_endangered":1,"region":"中国云南、西藏（高黎贡山、碧罗雪山）","description":"中国特有，国家一级保护动物。"},
    {"name_cn":"斑羚","name_en":"Chinese Goral","scientific_name":"Naemorhedus goral","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"斑羚属","species":"斑羚","subspecies":"","category":"哺乳动物","feature":"灰色毛发，喉部白色，善攀岩","is_endangered":1,"region":"中国东北、华北、华东山区","description":"国家二级保护动物。"},
    {"name_cn":"鬣羚","name_en":"Chinese Serow","scientific_name":"Capricornis milneedwardsii","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"鬣羚属","species":"鬣羚","subspecies":"","category":"哺乳动物","feature":"体型似羊又似驴，颈背有鬃毛，栖息于陡峭山崖","is_endangered":1,"region":"中国西南、秦岭山区","description":"国家一级保护动物。"},
    {"name_cn":"中华鬣羚","name_en":"Chinese Serow","scientific_name":"Capricornis sinensis","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"鬣羚属","species":"中华鬣羚","subspecies":"","category":"哺乳动物","feature":"中国特有，鬃毛明显，角短而直","is_endangered":1,"region":"中国华东、华中、华南山地","description":"国家一级保护动物。"},
    {"name_cn":"扭角羚","name_en":"Takin","scientific_name":"Budorcas taxicolor","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"牛科","genus":"扭角羚属","species":"扭角羚","subspecies":"","category":"哺乳动物","feature":"体型似牛又似羊，角先外弯再反转，毛色金黄","is_endangered":1,"region":"中国西南（四川、陕西、甘肃）","description":"国家一级保护动物。"},
    {"name_cn":"野驴","name_en":"Wild Ass","scientific_name":"Equus kiang","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"奇蹄目","family":"马科","genus":"野驴属","species":"藏野驴","subspecies":"","category":"哺乳动物","feature":"体型似骡，背部浅色纵纹，奔跑时群队形整齐","is_endangered":1,"region":"中国青藏高原（羌塘）","description":"国家一级保护动物。"},
    {"name_cn":"野马","name_en":"Przewalski's Horse","scientific_name":"Equus ferus przewalskii","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"奇蹄目","family":"马科","genus":"马属","species":"野马","subspecies":"","category":"哺乳动物","feature":"体型较小，毛色土黄，背部黑色鬃毛直立","is_endangered":1,"region":"中国新疆、甘肃（半散养）","description":"国家一级保护动物，野生种群已灭绝，保护性回归项目进行中。"},
    {"name_cn":"野猪","name_en":"Wild Boar","scientific_name":"Sus scrofa","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"猪科","genus":"猪属","species":"野猪","subspecies":"","category":"哺乳动物","feature":"体型粗壮，犬齿外露成獠牙，毛深褐色","is_endangered":0,"region":"中国各地","description":"三有保护动物。"},
    {"name_cn":"麝","name_en":"Musk Deer","scientific_name":"Moschus spp.","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"麝科","genus":"麝属","species":"原麝、林麝、马麝等","subspecies":"","category":"哺乳动物","feature":"无角，雄性有麝香腺，体毛粗糙，无胆囊","is_endangered":1,"region":"中国东北、西北、西南山区","description":"国家一级保护动物。"},
    {"name_cn":"麂子","name_en":"Muntjac","scientific_name":"Muntiacus spp.","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"麂属","species":"赤麂、黑麂等","subspecies":"","category":"哺乳动物","feature":"体型小，额部有簇毛，雄性有短角","is_endangered":0,"region":"中国华东、华南、西南","description":"国家三有保护动物。"},
    {"name_cn":"黑麂","name_en":"Black Muntjac","scientific_name":"Muntiacus crinifrons","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"麂属","species":"黑麂","subspecies":"","category":"哺乳动物","feature":"全身黑褐色，额部有蓬松长毛，中国特有","is_endangered":1,"region":"中国安徽、浙江、福建山区","description":"中国特有，国家一级保护动物。"},
    {"name_cn":"坡鹿","name_en":"Eld's Deer","scientific_name":"Rucervus eldii","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"豚鹿属","species":"坡鹿","subspecies":"","category":"哺乳动物","feature":"四肢细长，白色眼圈，雄鹿角特殊弯曲","is_endangered":1,"region":"中国海南（坝王岭）","description":"国家一级保护动物。"},
    {"name_cn":"梅花鹿","name_en":"Sika Deer","scientific_name":"Cervus nippon","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"鹿属","species":"梅花鹿","subspecies":"","category":"哺乳动物","feature":"体毛夏季红棕有白斑，冬季灰褐，冬季观赏价值高","is_endangered":1,"region":"中国东北、华东（江西有野生群）","description":"国家一级保护动物，吉林"东丰梅花鹿"著名。"},
    {"name_cn":"马鹿","name_en":"Red Deer","scientific_name":"Cervus elaphus","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"鹿属","species":"马鹿","subspecies":"","category":"哺乳动物","feature":"体型大，角大且多分叉，夏季毛色红褐","is_endangered":0,"region":"中国东北、西北、四川","description":"国家二级保护动物。"},
    {"name_cn":"水鹿","name_en":"Sambar Deer","scientific_name":"Rusa unicolor","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"水鹿属","species":"水鹿","subspecies":"","category":"哺乳动物","feature":"体型大善游泳，耳大面宽，夜间活动","is_endangered":0,"region":"中国华东、华南、西南","description":"国家二级保护动物。"},
    {"name_cn":"白唇鹿","name_en":"White-lipped Deer","scientific_name":"Cervus albirostris","kingdom":"动物界","phylum":"脊索动物门","class":"哺乳纲","order_name":"偶蹄目","family":"鹿科","genus":"鹿属","species":"白唇鹿","subspecies":"","category":"哺乳动物","feature":"唇周及下颌白色，高原特产，角型优美","is_endangered":1,"region":"中国青藏高原东部","description":"中国特有，国家一级保护动物。"},
    {"name_cn":"泽鹿","
